app:
  auth:
    encoding-id: argon2
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      access-token-expiry: 5m
      refresh-token-expiry: 24h
spring:
  data:
    redis:
      url: ${AIVEN_REDIS_URL}
      timeout: 2000ms
---
spring:
  config:
    activate:
      on-profile: dev
  security:
    user:
      name: user
      password: test